name: Call Supabase Function at Midnight

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  call-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Function
        run: >
          curl -X POST "https://"lsnvuplejqfxlraksfda.supabase.co/functions/v1/reset-notes"
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
